# Generated by Django 6.1.1 on 2026-10-03 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firs_name", models.CharField(max_length=50, verbose_name="نام")),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="نام خانوادگی"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="ایمیل")),
                ("phone", models.CharField(max_length=20, verbose_name="شماره تماس")),
                (
                    "github",
                    models.URLField(blank=True, verbose_name="لینک گیت\u200cهاب"),
                ),
                ("linkedin", models.URLField(blank=True, verbose_name="لینک لینکدین")),
                (
                    "summary",
                    models.TextField(blank=True, verbose_name="درباره من (خلاصه)"),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="تاریخ ثبت"),
                ),
            ],
            options={
                "verbose_name": "رزومه",
                "verbose_name_plural": "رزومه ها",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="مهارت"),
                ),
            ],
            options={
                "verbose_name": "مهارت",
                "verbose_name_plural": "مهارت ها",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="عنوان پروژه")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="توضیح کوتاه"),
                ),
                ("link", models.URLField(blank=True, verbose_name="لینک")),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="resumes.resume",
                    ),
                ),
            ],
            options={
                "verbose_name": "پروژه",
                "verbose_name_plural": "پروژه\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="عنوان")),
                (
                    "organization",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="سازمان یا مجموعه"
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="بازه\u200cی زمانی"
                    ),
                ),
                ("situation", models.TextField(blank=True, verbose_name="موقعیت")),
                ("task", models.TextField(blank=True, verbose_name="وظیفه")),
                ("action", models.TextField(blank=True, verbose_name="اقدام")),
                ("result", models.TextField(blank=True, verbose_name="نتیجه")),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiences",
                        to="resumes.resume",
                    ),
                ),
            ],
            options={
                "verbose_name": "تجربه",
                "verbose_name_plural": "تجربه\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "university",
                    models.CharField(max_length=100, verbose_name="دانشگاه"),
                ),
                ("field", models.CharField(max_length=100, verbose_name="رشته")),
                (
                    "degree",
                    models.CharField(
                        choices=[
                            ("associate", "کاردانی"),
                            ("bachelor", "کارشناسی"),
                            ("master", "کارشناسی ارشد"),
                            ("phd", "دکتری"),
                        ],
                        max_length=20,
                        verbose_name="مقطع",
                    ),
                ),
                (
                    "start_year",
                    models.CharField(max_length=10, verbose_name="سال ورود"),
                ),
                (
                    "end_year",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        verbose_name="سال پایان (خالی = در حال تحصیل)",
                    ),
                ),
                (
                    "gpa",
                    models.CharField(blank=True, max_length=10, verbose_name="معدل"),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="educations",
                        to="resumes.resume",
                    ),
                ),
            ],
            options={
                "verbose_name": "تحصیلات",
                "verbose_name_plural": "تحصیلات",
            },
        ),
        migrations.CreateModel(
            name="Award",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="عنوان")),
                (
                    "issuer",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="نهاد صادرکننده"
                    ),
                ),
                (
                    "date",
                    models.CharField(blank=True, max_length=30, verbose_name="تاریخ"),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awards",
                        to="resumes.resume",
                    ),
                ),
            ],
            options={
                "verbose_name": "افتخار یا گواهینامه",
                "verbose_name_plural": "افتخارات و گواهینامه\u200cها",
            },
        ),
        migrations.AddField(
            model_name="resume",
            name="skills",
            field=models.ManyToManyField(
                blank=True, to="resumes.skill", verbose_name="مهارت\u200cها"
            ),
        ),
    ]
