# Generated by Django 6.1.1 on 2026-10-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="collaboration",
            field=models.CharField(
                blank=True,
                max_length=150,
                verbose_name="نوع همکاری با دانشگاه (مثلاً عضو انجمن، دستیار آموزشی، پژوهشگر)",
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="status",
            field=models.CharField(
                choices=[
                    ("student", "دانشجوی فعلی"),
                    ("graduate_collab", "فارغ\u200cالتحصیل و همکار دانشگاه"),
                    ("graduate", "فارغ\u200cالتحصیل"),
                ],
                default="student",
                max_length=20,
                verbose_name="وضعیت",
            ),
        ),
    ]
