# Generated by Django 6.1.1 on 2026-10-03 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0002_resume_collaboration_resume_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resume",
            old_name="firs_name",
            new_name="first_name",
        ),
    ]
