# Generated by Django 6.1.1 on 2026-10-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0003_rename_firs_name_resume_first_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="award",
            name="link",
            field=models.URLField(blank=True, verbose_name="لینک مدرک یا گواهینامه"),
        ),
    ]
