# Generated by Django 6.1.1 on 2026-10-04 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0004_award_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="حوزه"),
                ),
            ],
            options={
                "verbose_name": "حوزه\u200cی علاقه",
                "verbose_name_plural": "حوزه\u200cهای علاقه",
            },
        ),
        migrations.AddField(
            model_name="resume",
            name="interests",
            field=models.ManyToManyField(
                blank=True,
                to="resumes.interest",
                verbose_name="حوزه\u200cهای مورد علاقه",
            ),
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="زبان")),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("basic", "مقدماتی"),
                            ("intermediate", "متوسط"),
                            ("advanced", "پیشرفته"),
                            ("fluent", "مسلط"),
                            ("native", "زبان مادری"),
                        ],
                        max_length=20,
                        verbose_name="سطح",
                    ),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="languages",
                        to="resumes.resume",
                    ),
                ),
            ],
            options={
                "verbose_name": "زبان",
                "verbose_name_plural": "زبان\u200cها",
            },
        ),
    ]
