# Generated by Django 6.1.1 on 2026-10-05 06:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0005_interest_resume_interests_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="pdf",
            field=models.FileField(
                blank=True, upload_to="resume_pdfs/", verbose_name="فایل PDF"
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="token",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
