# Generated by Django 6.1.1 on 2026-10-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0006_resume_pdf_resume_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="other_skills",
            field=models.CharField(
                blank=True, max_length=1000, verbose_name="مهارت\u200cهای دیگر"
            ),
        ),
    ]
