# Generated by Django 6.1.1 on 2026-10-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0008_seed_skills_interests"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="future_plan",
            field=models.TextField(blank=True, verbose_name="برنامه\u200cی آینده"),
        ),
        migrations.AddField(
            model_name="resume",
            name="work_conditions",
            field=models.TextField(blank=True, verbose_name="شرایط کاری مورد نظر"),
        ),
    ]