# Generated by Django 6.1.1 on 2026-10-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0009_resume_future_plan_resume_work_conditions"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="شرایط کاری"
                    ),
                ),
            ],
            options={
                "verbose_name": "شرایط کاری",
                "verbose_name_plural": "شرایط کاری",
            },
        ),
        migrations.RemoveField(
            model_name="resume",
            name="work_conditions",
        ),
        migrations.AddField(
            model_name="resume",
            name="work_types",
            field=models.ManyToManyField(
                blank=True,
                to="resumes.workcondition",
                verbose_name="شرایط کاری مورد نظر",
            ),
        ),
    ]
